django-app/datadictionary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django/admin/', admin.site.urls),
    path('', include("dictionary.urls")),
]

django-app/dictionary/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # All User View Routes
    path('', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('_handle_user/', views.handle_user,  name='handleUser'),
    path('about_cata', views.about_cata, name="aboutCata"),
    
    
    # Admin View Page Routes
    path('admin/manage_users/', views.manage_users, name="manageUsers"),
    path('admin/ingest/database/', views.rdbms_view, name="ingestData"),
    path('admin/ingest/flatfile/', views.process_csv, name="process_csv"),


    # RDBMS
    path('admin/process/rdbms/', views.rdbms_process, name="processRdbms"),
    path('admin/ingest/rdbms/', views.rdbms_ingestion, name="ingestRdbms"),


    # Manage Tables Routes
    path('admin/manage_tables/', views.manage_tables, name="manageTables"),
    path('admin/manage_tables/view/<int:groupId>', views.view_tables, name="viewTables"),
    path('admin/manage_tables/archive/<int:groupId>', views.archived_group, name="archivedGroup"),


    # Annotation Columns Routes API
    path('admin/annotate/<int:groupId>', views.annotation_save, name="annotationColumn"),
    

    # Admin User Action Routes
    path('admin/user/create/', views.create_user, name="createUser"),
    path('admin/user/delete/<int:userId>', views.delete_user, name="deleteUser"),
    path('admin/user/edit/', views.edit_user, name="editUser"),
    path('admin/user/fetch/<int:userId>', views.fetch_user, name="fetchUser"),
    

    #Generate template
    path('generate_template/', views.generate_template, name='generate_template'),

]

django-app/dictionary/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

# Custom User Manager model
class CustomUserManager(BaseUserManager):

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)
    
# Custom User Model
class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    is_visible = models.BooleanField(default=True)  # New field to represent user visibility
    is_active = models.BooleanField(default=True)  # New field to represent user activation


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class GroupTable(models.Model):
    group_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)
    schema_num = models.IntegerField(null=False, default=0)
    table_num = models.IntegerField(null=False, default=0)
    column_num = models.IntegerField(null=False, default=0)
    is_archived = models.BooleanField(null=False, blank=False, default=False)

# Table model      
class Table(models.Model):
    table_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)
    group = models.ForeignKey(GroupTable, on_delete=models.CASCADE, db_column='group_id')

# Column model
class Column(models.Model):
    column_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)
    sample = models.TextField(blank = True)
    datatype = models.CharField(max_length=255, null=False)
    table = models.ForeignKey(Table, on_delete=models.CASCADE, db_column='table_id')
    
# Annotation model
class Annotation(models.Model):
    annotation_id = models.AutoField(primary_key=True)
    comments = models.TextField(null=True, blank = True)
    timestamp = models.DateTimeField(auto_now_add=True)
    email = models.ForeignKey(CustomUser, on_delete=models.CASCADE, db_column='id')
    column = models.ForeignKey(Column, null=True, on_delete=models.SET_NULL, db_column='column_id')

    class Meta:
        get_latest_by = 'timestamp' 

django-app/templates/user_pages/dashboard/manage_table/manage_table.html
{% extends 'base_sidebar.html' %}
{% load static %}
{% block style %}

<style>
  .table-header {
    background-color: #65a3c4;
    border-radius: 8px;
  }
  .table.table-hover {
    border-radius: 8px;
  }
  
  body {
    background-color: #EBF2EA;
  }
  
  tbody {
    background-color: white;
  }
  
  .mr-auto+.ms-auto {
    margin-left: 5px;
  }
  .active-tab {
    background-color: #65A3C4 !important;
  }
  .tbl-container {
    margin-top: 10px;
    margin-left: 10px;
  }
  
  .bdr {
    border-radius: 6px;
    overflow: hidden;
  }
  .tbl-container {
    margin-top: 50px;
    margin-left: 30px;
    max-width: 1050px;
    max-height: 550px; /* Set your desired height */
    overflow-y: auto; /* Enable vertical scrolling */
    overflow-x: hidden; /* Optional: Disable horizontal scrolling */
  }
  .btn-custom {
    width: 180px;
    height: 48px;
    flex-shrink: 0;
    border-radius: 1px;
    background: #00241B;
    
  }
  
  .btn-archive{
    background-color: #FBE7E4; 
    color: #952D2D;
  }
  
  /* Add this CSS to style the archived rows */
  .archived-row {
    background-color: #dddddd !important;
    color: #888888 !important;
  }
  
</style>

{% endblock %}

{% block active_tab_manageTables %}
active active-tab
{% endblock %}

{% block content%}
<div class="container" style="color: #0077B6; font-size: 32px; font-family: 'Fira Sans', sans-serif; font-style: normal; font-weight: 700; line-height: normal; text-transform: capitalize;">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb" style="position: absolute; top: 10%; margin-left: 15%; transform: translate(-50%, -50%); text-align: center; font-size: 25px; font-family: 'Fira Sans', sans-serif; font-style: normal; font-weight: 700; line-height: normal; text-transform: capitalize;">
      <li class="breadcrumb-item active" aria-current="page"> <a style="color: #0077B6;">Metadata Sources</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a style="color: #0077B6;">Metadata</a></li>
    </ol>
  </nav>
</div>

<!--METADATA TABLE-->
<div class="container" style="position: absolute; top: 48%; left: 60%;  width: 75%; transform: translate(-50%, -50%);">
  <div class="tbl-container bdr">
    <table class="table table-hover">
      <thead class="table-header" style="background-color: #65A3C4; color: #EBF2EA;border-radius: 8px;">
        <tr>
          <th scope="col" style="background-color: #65A3C4; color: #EBF2EA; width: 30%;">Name</th>
          <th scope="col" style="background-color: #65A3C4; color: #EBF2EA; width: 12%;"># of Schema</th>
          <th scope="col" style="background-color: #65A3C4; color: #EBF2EA; width: 12%;">Tables</th>
          <th scope="col" style="background-color: #65A3C4; color: #EBF2EA; width: 15%;">Actions</th>
        </tr>
      </thead>
      <tbody >
        {% for group in groups %}
        {% if request.user.groups.first.name != "Admin" and not group.is_archived %}
        <tr id="row-{{group.group_id}}">
          <td><span class="ms-2">{{ group.name }}</span></td>
          <td><span class="ms-2">{{ group.schema_num }}</span></td>
          <td><span class="ms-2">{{ group.table_num }}</span></td>
          <td>
            <a class="btn" style="background-color: #F1FBE4; color: #65A3C4;--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" href="{% url 'viewTables' group.group_id %}">View</a>
          </td>
        </tr>
        {% elif request.user.groups.first.name == "Admin" %}
        <tr id="row-{{group.group_id}}">
          <td class="{% if group.is_archived %}archived-row{% endif %}"><span class="ms-2">{{ group.name }}</span></td>
          <td class="{% if group.is_archived %}archived-row{% endif %}"><span class="ms-2">{{ group.schema_num }}</span></td>
          <td class="{% if group.is_archived %}archived-row{% endif %}"><span class="ms-2">{{ group.table_num }}</span></td>
          <td class="{% if group.is_archived %}archived-row{% endif %}">
            <a class="btn" style="background-color: #EBF2EA; color: #0077B6;--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" href="{% url 'viewTables' group.group_id %}">View</a>
            {% if group.is_archived %}
            <button type="button" class="btn btn-success" id="archiveBtn-{{group.group_id}}" onclick="archiveGroup({{ group.group_id }})" style=" --bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem; background-color: #0077B6;">Restore</button>
            {% else %}
            <button type="button" class="btn btn-archive" id="archiveBtn-{{group.group_id}}" onclick="archiveGroup({{ group.group_id }})" style=" --bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Archive</button>
            {% endif %}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>



<div id="successMessage" class="toast" style="position: absolute; top: 20px; right: 20px; z-index: 9999;">
  <div class="toast-header" style="background-color: #9BCBC8; color: #FAF3DD;">
    <strong class="mr-auto">Success</strong>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body" style="background-color: white; color: #0077B6;">
    Data saved successfully!
  </div>
</div>


<script>
  function archiveGroup(groupId){
    $.ajax({
      url: 'http://localhost/admin/manage_tables/archive/'+groupId,
      success: function(response){
        var data = JSON.parse(response);
        var trElement = $("#row-" + groupId);
        var tdElements = trElement.find("td");
        var archiveBtn = $("#archiveBtn-" + groupId);
        tdElements.toggleClass("archived-row", data);
        archiveBtn
        .removeClass(data ? "btn-archive" : "btn-success")
        .addClass(data ? "btn-success" : "btn-archive")
        .text(data ? "Restore" : "Archive");
        
        toastr.success(data ? 'The Datapoint has been archived' : 'The Datapoint has been restored');
      }
    });
  }
  
  
  
  var option = {
    animation: true,
    delay: 2000
  };
  
  function Toasty() {
    var toastHTMLElement = document.getElementById("EpicToast");
    var toastElement = new bootstrap.Toast(toastHTMLElement, option);
    toastElement.show();
  }
  function saveForm(){
    var formValue = document.getElementById("message-text").value;
    
    //Perform saving logic here like send the form value to a server using AJAX, Display a success message or perform any desired actions -->
    var successMessage = document.getElementById("successMessage");
    var bootstrapToast = new bootstrap.Toast(successMessage);
    bootstrapToast.show();
    
    setTimeout(function() {
      bootstrapToast.hide();
    }, 3000);
    
    var modal = document.getElementById("exampleModal");
    var bootstrapModal = bootstrap.Modal.getInstance(modal);
    bootstrapModal.hide();
  }
</script>

{% endblock %}

django-app/templates/user_pages/dashboard/manage_table/view_table.html
{% extends 'base_sidebar.html' %}
{% load static %}

{% block style %}
<style>
  .table-header {
    background-color: #65A3C4;
    border-radius: 8px;
  }
  
  .table.table-hover {
    border-radius: 8px;
  }
  
  body {
    background-color: #EBF2EA;
  }
  
  tbody {
    background-color: white;
  }
  
  .mr-auto+.ms-auto {
    margin-left: 5px;
  }
  
  .active-tab {
    background-color: #65A3C4 !important;
  }
  
  
  .bdr {
    border-radius: 6px;
    overflow: hidden;
  }
  
  .breadcrumb-item a {
    color: #0077B6;
  }
  
  .display-5 {
    color: #0077B6;
    text-align: center;
    font-size: 32px;
    font-family: 'Fira Sans', sans-serif;
    font-style: normal;
    font-weight: 700;
    line-height: normal;
    text-transform: capitalize;
  }
  
  .input-group {
    margin-bottom: 10px;
  }
  
  .form-outline {
    position: relative;
  }
  
  .form-outline input {
    padding-right: 40px;
  }
  
  .form-outline label {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    font-size: 14px;
    color: #495057;
    -webkit-transition: 0.2s;
    transition: 0.2s;
  }
  
  .form-outline input:focus ~ label,
  .form-outline input:valid ~ label {
    font-size: 12px;
    top: -20px;
    left: 0;
    color: #4A7C59;
  }
  
  .btn-outline-light {
    background-color: #68b0ab;
    color: #f1fbe4;
  }
  
  .btn-outline-light:hover {
    background-color: #4A7C59;
  }
  
  .table-header th {
    background-color: #8FC0A9;
    color: #FAF3DD;
  }
  
  .table td span {
    display: inline-block;
    min-width: 100px;
    padding-left: 10px;
  }
  
  .pagination {
    justify-content: center;
  }
  
  .pagination .page-item.disabled .page-link {
    color: #6c757d;
    pointer-events: none;
    background-color: #FAF3DD;
    border-color: #dee2e6;
  }
  
  .pagination .page-link {
    color: #4A7C59;
    background-color: #FAF3DD;
    border-color: #dee2e6;
  }
  
  .pagination .page-link:hover {
    color: #fff;
    background-color: #68b0ab;
    border-color: #68b0ab;
  }
  
  .pagination .page-item.active .page-link {
    z-index: 3;
    color: #fff;
    background-color: #68b0ab;
    border-color: #68b0ab;
  }
  
  .text-center {
    text-align: center;
    
  }
  .spacer {
    width: 50%; /* Adjust the value to control the spacing */
  }
  
  .dataTables_filter input {
    width: 65%;
    margin-bottom: 1em;
  }
  
  .dataTables_wrapper {
    margin-top: 1.5em; 
  }
  
  table.dataTable thead>tr>th.sorting {
    background-color: #8FC0A9;
    color:#FAF3DD;
    padding: 0.7em;
  }
  
  .dataTables_length select{
    background-color: black;
  }
  
</style>
{% endblock %}

{% block active_tab_manageTables %}
active active-tab
{% endblock %}

{% block content %}
<div class="container" style="color: #0077B6; font-size: 32px; font-family: 'Fira Sans', sans-serif; font-style: normal; font-weight: 700; line-height: normal; text-transform: capitalize;">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb" style="position: absolute; top: 10%; margin-left: 26.5%; transform: translate(-50%, -50%); text-align: center; font-size: 25px; font-family: 'Fira Sans', sans-serif; font-style: normal; font-weight: 700; line-height: normal; text-transform: capitalize;">
      <li class="breadcrumb-item active" aria-current="page"> <a style="color: #0077B6;">Metadata Sources</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a style="color: #0077B6;">Metadata</a></li>
      <li class="breadcrumb-item active" aria-current="page"> <a style="color: #03045E;">View {{ datasource }} </a></li>
    </ol>
  </nav>
</div>

<div class="container" style="margin-top: 10%;">
  <div class="row">
    <div class="col text-center">
      <div class="container">
        <div class="d-flex justify-content-between" style="width: 100%;">
          <div class="spacer"></div>
          {% if request.user.groups.first.name != 'Reader' %}
          <div class="d-flex justify-content-end" style="width: 20%;">
            <input type="hidden" id="csrf" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            <input type="hidden" name="annotation" id="annotationInput" value="[]">
            <button type="button" onclick="annotationSave()" id="annotationSaveBtn" class="btn btn-outline-light"  style="background-color:  #0077B6; color: #EBF2EA;">
              <i class="fas fa-save"></i> Save
            </button>
          </div>
          {% endif %}
        </div>
      </div>
  {% for table in tables %}
  <div class="container bdr">
    <h3 class="mt-5 h5 fw-bold" style="color:#0077B6;text-align: left;">{{ table.name }}</h3>
    <table class="table row-border compact" style="width:100%">
      <thead>
        <tr>
          <th scope="col" style="background-color: #65A3C4; color:#EBF2EA;">Column Name</th>
          <th scope="col" style="background-color: #65A3C4; color:#EBF2EA;">Data Type</th>
          <th scope="col" style="background-color: #65A3C4; color:#EBF2EA;">Sample Data</th>
          <th scope="col" style="background-color: #65A3C4; color:#EBF2EA;">Annotation</th>
        </tr>
      </thead>
      <tbody>
        {% for column in table.column_set.all %}
        <tr>
          <td class="px-2">{{ column.name }}</td>
          <td class="px-2">{{ column.datatype }}</td>
          {% if column.sample|length >= 25 %}
          <td class="px-2">{{ column.sample|slice:":25" }} ...</td>
          {% else %}
          <td class="px-2">{{ column.sample }}</td>
          {% endif %}
          <td>
            <div class="form-group">
              {% with latest_annotation=column.annotation_set.latest %}
              {% if latest_annotation %}
              <textarea class="form-control" name="annotationText" id="{{ column.column_id }}" row="1" {% if request.user.groups.first.name == 'Reader' %}disabled{% endif %}>{{ latest_annotation.comments }}</textarea>
              <span id="log-name-{{ column.column_id }}" class="text-muted" style="font-size:0.5em">Last Modifier: {{ latest_annotation.email.first_name }} {{ latest_annotation.email.last_name }}</span>
              <span id="log-email-{{ column.column_id }}" class="text-danger" style="font-size:0.5em">({{ latest_annotation.email.email}})</span>
              {% else %}
              <textarea class="form-control" name="annotationText" id="{{ column.column_id }}" row="1" {% if request.user.groups.first.name == 'Reader' %}disabled{% endif %}></textarea>
              <span id="log-name-{{ column.column_id }}" class="text-muted" style="font-size:0.5em"></span>
              <span id="log-email-{{ column.column_id }}" class="text-danger" style="font-size:0.5em"></span>
              {% endif %}
              {% endwith %}
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </div></div>
  {% endfor %}


<script>
  var editChange = [];
  $("textarea[name='annotationText']").on("change", function(){
    editChange.push({'id': $(this).attr("id"), 'annotate':$(this).val()});
    $("#annotationInput").val(JSON.stringify(editChange));
  });
  
  function annotationSave(){
    var data =  $("#annotationInput").val();
    var csrf = $("#csrf").val();
    $.ajax({
      url: "{% url 'annotationColumn' groupId %}",
      method: 'post',
      data: {
        annotation : data,
        csrfmiddlewaretoken: csrf
      },
      success: function(response){
        var dataParse = JSON.parse(JSON.stringify(response));
        for(var i=0; i<dataParse.length; i++){
          var name = "Last Modifier: "+ dataParse[i].name;
          $("#log-name-"+dataParse[i].id).text(name);
          $("#log-email-"+dataParse[i].id).text("("+dataParse[i].email+")");
        }
        toastr.success('Annotation saved successfully');
      },
    });
  };
  
  var datatable = new DataTable('.table');
</script>
{% endblock %}